### ISSUE TITLE
02-bootstrap.md omits discussion of populating the q param

### ISSUE THREAD

**Issue by rhuffstedtler** [mikecrittenden/drupal-7-deconstructed#3]
In 03-router.md you mention that the bootstrap process has converted the visitor friendly path into the q parameter, but you didn't actually say where that happens when you were discussing bootstrap.

So, while I agree that drupal_environment_initialize() isn't the sexiest function, it becomes a lot more interesting the first time one encounters an installation where clean urls aren't working. :-) 

I recommend expanding that section of 02-bootstrap.md to cover it.

**Comment by crittermike** [comment]
"you didn't actually say where that happens when you were discussing bootstrap." I thought I made it fairly clear here? https://github.com/mikecrittenden/drupal-7-deconstructed/blob/master/02-bootstrap.md#initializes-the-path - no good?

That said, after taking a second look, I agree that the omission of `$_GET ['q'] = request_path();` in `drupal_environment_initialize()` and diving into what happens in `request_path()` is a pretty big missing piece. I'll add some info on that.

**Comment by rhuffstedtler** [comment]
Thanks.

BTW, in the following line you have a spelling error:

"alter the inboud URL"

should be "alter the inbound URL"

**Comment by crittermike** [comment]
Hey @rhuffstedtler, how does that commit look? Feel free to close this issue if you're happy with it, but don't be shy if you're not.

P.S. That typo was fixed in another commit.

Thanks again!

**Comment by rhuffstedtler** [comment]
That's excellent. The specifics you gave make it really clear about the situations in core that trigger it, and establish a pretty good conceptual basis for thinking about when else it might happen.
